---
- hosts: all
  become: yes
  tasks:
    - name: Install NTP package
      package:
        name: ntp
        state: present
    - name: Enter ntp master and Copy
      copy:
        src: /etc/ntp.conf23
        dest: /etc/ntp.conf
        mode: 0644
      ignore_errors: yes
    - name: Start ntp service
      service:
        name: ntpd
        state: started
